################
### HYPRLAND ###
################

source = ~/.config/hypr/modules/monitors.conf
source = ~/.config/hypr/modules/programs.conf
source = ~/.config/hypr/modules/autostart.conf
source = ~/.config/hypr/modules/env.conf
source = ~/.config/hypr/modules/decorations.conf
source = ~/.config/hypr/modules/animations.conf
source = ~/.config/hypr/modules/windowrules.conf
source = ~/.config/hypr/modules/input.conf
source = ~/.config/hypr/modules/binds.conf

#############
### THEME ###
#############

source = ~/.config/hypr/themes/dracula/dracula.conf

general {
    col.active_border   = $border_active $pink 45deg
    col.inactive_border = $border_inactive
}


group {
    col.border_active   = $purple $pink 45deg
    col.border_inactive = $bg_alt
}

source = ~/.config/hypr/themes/catppuccin/mocha.conf

general {
    col.active_border = $border_active
    col.inactive_border = $border_inactive
}
